version: '3.8'

services:
  database:
    container_name: "oemoem-notesdb"
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_notes

